pihole_timezone: "Europe/London"
pihole_webpassword: "{{ vault_pihole_webpassword }}"

pihole_custom_blocklists:
  # Default
  - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

  # Aggressive ad blocking
  - "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt"

  # Hagezi
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt"
  - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt"

  # Tracking and telemetry
  - "https://v.firebog.net/hosts/Easyprivacy.txt"
  - "https://v.firebog.net/hosts/Prigent-Ads.txt"

  # Malicious domains
  - "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt"
  - "https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt"

  # Phishing
  - "https://phishing.army/download/phishing_army_blocklist_extended.txt"

  # Suspicious/scam sites
  - "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt"
