$ANSIBLE_VAULT;1.1;AES256
39623561333562653436666665316131303862643039366130343034333838626161663038653639
3063393063663331326139333832623539323836653535620a303936333837366330343662346134
61346337623366363766373532366430623766663861653738383637336530623337653533623436
3938353734633937620a393438376165623935626536333762366463336536643864633237316234
37653137633635313063363930623034303635383665393330363536313936306639353337326461
39373064656536343535383932366161376631383335336533393931663037303538336161653032
633332333834303730333334323461316462
