- name: Provision PVE Netcore
  hosts: netcore
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
  roles:
    - role: common
    - role: firewall
    - role: docker
    - role: unbound
    - role: pihole
